spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/immoluxe
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  file:
    uploads:
      photos-output-path: ./uploads
  server:
    url: http://localhost:8080/api/v1
    port: 8088
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/immo-luxe"
